teamName: kubrix
appName: my-appname-demo
repoUrl: https://github.com/DeveloperKube/kubrix-my-appname-demo
createAppNamespace: true
stages:
  - name: "test"
    requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse-{{ .Values.appName }}
      sources:
        direct: true
  - name: "qa"
    requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse-{{ .Values.appName }}
      sources:
        stages:
        - test
  - name: "prod"
    requestedFreight:
    - origin:
        kind: Warehouse
        name: warehouse-{{ .Values.appName }}
      sources:
        stages:
        - qa
